//! Tests lesspass.rs using lesspass-cli as oracle.
//!
//! The test vectors in this file are generated by lesspass-cli using
//! the script `make-blackbox-tests.sh` located in the same directory
//! as this test.
use lesspass::*;

pub fn generate(
    website: &str,
    login: &str,
    password: &str,
    counter: u32,
    length: usize,
    charset: CharacterSet,
) -> String {
    let salt = generate_salt(website, login, counter);
    let entropy = generate_entropy(password, &salt, Algorithm::SHA256, 100000);
    render_password(&entropy, charset, length)
}

fn t(
    _n: usize,
    website: &str,
    login: &str,
    password: &str,
    counter: u32,
    length: usize,
    passwords: &[&str],
) {
    let mut i = 0;
    for &lower in &[false, true] {
        for &upper in &[false, true] {
            for &digits in &[false, true] {
                for &symbols in &[false, true] {
                    if !lower && !upper && !digits && !symbols {
                        continue;
                    }
                    // Start with the empty set.
                    let mut charset = CharacterSet::Lowercase & !CharacterSet::Lowercase;

                    if lower {
                        charset |= CharacterSet::Lowercase;
                    }
                    if upper {
                        charset |= CharacterSet::Uppercase;
                    }
                    if digits {
                        charset |= CharacterSet::Numbers;
                    }
                    if symbols {
                        charset |= CharacterSet::Symbols;
                    }
                    assert_eq!(
                        generate(website, login, password, counter, length, charset),
                        passwords[i],
                        "Mismatch for website: {:?}, login: {:?}, \
                         password: {:?}, counter: {:?}, length: {:?}, \
                         lower: {:?}, upper: {:?}, digits: {:?}, \
                         symbols: {:?}",
                        website,
                        login,
                        password,
                        counter,
                        length,
                        lower,
                        upper,
                        digits,
                        symbols
                    );
                    i += 1;
                }
            }
        }
    }
}

#[test]
fn vectors_000() {
    t(
        0,
        "example.org",
        "user@example.org",
        "password",
        1,
        12,
        &[
            ".;#+]<`.:.^[",
            "565301097089",
            "@95:&/=`91.,",
            "LFOTFIGTSMDD",
            "FXZ,LY:::WF.",
            "ZZDN0999N51D",
            "\"0C6!6O;6P&9",
            "lfotfigtsmdd",
            "fxz,ly:::wf.",
            "zzdn0999n51d",
            "\"0c6!6o;6p&9",
            "LcKfxZFrkJzv",
            "@.`-JuB_+_uq",
            "BdNBGqC3wMmO",
            "X%W(PxH#j7_2",
        ],
    );
}

#[test]
fn vectors_001() {
    t(
        1,
        "example.org",
        "user@example.org",
        "password",
        1,
        16,
        &[
            ".;>#+]<`.:.[^&#!",
            "5653901097890787",
            "@$5:&/=`91,(3911",
            "LFOTMFITSMDDGWYP",
            "XZ,~LYH::WF.:.:D",
            "ZZDN0999H5D5AQ9B",
            "1\"0U6!6OP&9'R>;R",
            "lfotmfitsmddgwyp",
            "xz,~lyh::wf.:.:d",
            "zzdn0999h5d5aq9b",
            "1\"0u6!6op&9'r>;r",
            "LXcKfxZFrzzvKeQz",
            "@'.`-wB_+Iuqgu&y",
            "BNGqCpwM7MmO3Pd1",
            "(XW(Px#_z27Dk>5a",
        ],
    );
}

#[test]
fn vectors_002() {
    t(
        2,
        "example.org",
        "user@example.org",
        "password",
        1,
        32,
        &[
            ".;#+]<`.:.[~^&#!>?\"%%'.!(+!\\<{\"~",
            "56530109789078799086191172354593",
            "@5:&/=`91,(31111|0-~$2%)`7025)>.",
            "LFOTFITSMDDDGWYPMHAGZKZEBCUXJIAI",
            "XZ,LY::WF.+:.:GD@&_<N~\"@W]{'O-H!",
            "ZZDN09995UD5AQBZCJJFS7VHPFD9S4BG",
            "\"06!6OP&49'R!H>R=8P|DQL*U]`YDPG}",
            "lfotfitsmdddgwypmhagzkzebcuxjiai",
            "xz,ly::wf.+:.:gd@&_<n~\"@w]{'o-h!",
            "zzdn09995ud5aqbzcjjfs7vhpfd9s4bg",
            "\"06!6op&49'r!h>r=8p|dql*u]`ydpg}",
            "LcKfxZFrzvKeQzZLLsBzNRwXTTOoCpkZ",
            "@.D<`-B_+uqgu&y_KkcqtOM*K>iiMiVH",
            "BNGqCkw7MJmO3Pd1B0skLfZzZbEl989K",
            "XW(Px#<_27k>ahT+t+\"Ifp#6;2vb(b2E",
        ],
    );
}

#[test]
fn vectors_003() {
    t(
        3,
        "example.org",
        "user@example.org",
        "password",
        8,
        12,
        &[
            "!|>:\">{--^+'",
            "124970392575",
            ">0)<=`-#3\\=^",
            "HJLOJGIGVVRI",
            ":]'L<TLQ<?='",
            "V3AG629PG33C",
            "3Y?+RE9#L,DL",
            "hjlojgigvvri",
            ":]'l<tlq<?='",
            "v3ag629pg33c",
            "3y?+re9#l,dl",
            "HRcIspkALRdJ",
            ",nDaF_IUt*H]",
            "rZmMQiTwx8wy",
            "xnmA82EGfH#%",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_004() {
    t(
        4,
        "example.org",
        "user@example.org",
        "password",
        8,
        16,
        &[
            "|>:\">{.--^+'!!$=",
            "3124970925753704",
            "6>0)<=`?#\\=^7#5(",
            "HJLOIJGIGVRIVSAY",
            ":'L<T*LA<?='EOA%",
            "93AG6U2PG33CH8GY",
            "3Y?+R&E,DI4L.,<-",
            "hjloijgigvrivsay",
            ":'l<t*la<?='eoa%",
            "93ag6u2pg33ch8gy",
            "3y?+r&e,di4l.,<-",
            "wHRNcskALRdJpesT",
            "MDa_I(Utz*H]:MwS",
            "rM1cQiTNwxwyCBia",
            "gxnm>2FEGH1%TWok",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_005() {
    t(
        5,
        "example.org",
        "user@example.org",
        "password",
        8,
        32,
        &[
            "|>:\">{--^+'!!$=\".?{^/_>^~%<_&~+'",
            "01249709257537043022281523923401",
            ">0)<=`#\\*=^7#15(/./2#]\"$:$1*&_64",
            "HJLOJGIGVRIVSAYILIPNJOSLDOTBQLIV",
            ":'?L<TL<?='EOA%KW<|%$@#K#`QBSD%_",
            "3AG62PG33CH0Z8GYWAVD5MXBODW56U5N",
            "3Y?+RE,DL.N,<-AFH3$M1$IES\"O2L03}",
            "hjlojgigvrivsayilipnjosldotbqliv",
            ":'?l<tl<?='eoa%kw<|%$@#k#`qbsd%_",
            "3ag62pg33ch0z8gywavd5mxbodw56u5n",
            "3y?+re,dl.n,<-afh3$m1$ies\"o2l03}",
            "HRcskALRdJpegsTWGOkyzzRCJazRoELm",
            "Da_IUt*/rH]:MwSniU<`lOeio+JVG>Lp",
            "rMQiTwxuwyCBiaactwZw4iUbXkIpfcI5",
            "x(nm52EGH%TWok!<1HE-u@Y5K4_O+DY>",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_006() {
    t(
        6,
        "example.org",
        "user@example.org",
        "password",
        32,
        12,
        &[
            "|_=\\<_<{}}[*",
            "126629594742",
            "7,1680?[{}!]",
            "RYLYKRSJLPPM",
            "(_J&SOONY#V~",
            "ZN15PQU3OU3D",
            "H4|9@ZGF]T`@",
            "rylykrsjlppm",
            "(_j&soony#v~",
            "zn15pqu3ou3d",
            "h4|9@zgf]t`@",
            "rZpgBwSWXmkB",
            "HXFa&-&'p?gA",
            "m5XAcuh3Mfz3",
            "|j`-IBFW\"T6.",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_007() {
    t(
        7,
        "example.org",
        "user@example.org",
        "password",
        32,
        16,
        &[
            "|_=;\\<_{}}[*<'{;",
            "1266295947244643",
            "7,1840#?[{}]640@",
            "RYLYRISJLPPMKMZX",
            ")(_JOONFY#V~+G|F",
            "ZEN154PQU3UDU25F",
            "|=9@ZGFTQ`0@DDE&",
            "rylyrisjlppmkmzx",
            ")(_joonfy#v~+g|f",
            "zen154pqu3udu25f",
            "|=9@zgftq`0@dde&",
            "rZpgBwSXmBkMYxxX",
            "XFai-&'?g+FAL^H;",
            "5AcuhMfb7z38Jd2i",
            "|`BFvW\"T./9Dvcu#",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_008() {
    t(
        8,
        "example.org",
        "user@example.org",
        "password",
        32,
        32,
        &[
            "|_=\\<_{}}[*<'{;;=.)__]=!__*;*`=@",
            "12662959647246434672174967566567",
            "7,180?[{}2]640@2$12%*6@#.\\{7%**/",
            "QRYLYRSJLPPMKMZXIQVPQGLTJUKMBBZI",
            "(_J_JOONY#V~+G|FL\"(>#_B_$-HYW(B_",
            "ZN15PQU31UDU25FQOPTE5R3MINI5CIJL",
            "|9@Z'GFT`@DDE&!JZ\"OH@15?Y^'1MG`(",
            "qrylyrsjlppmkmzxiqvpqgltjukmbbzi",
            "(_j_joony#v~+g|fl\"(>#_b_$-hyw(b_",
            "zn15pqu31udu25fqopte5r3mini5cijl",
            "|9@z'gft`@dde&!jz\"oh@15?y^'1mg`(",
            "rZpgBwRSXmBkYxXxTawfIrGHZLewlDWO",
            "XFaW-&'?zgAL^H;};T)o-[#Vl(Z*'^X~",
            "85AcXuhMfz38d2irzeDKhIPnJFfd9T9b",
            "|`BFW\"T.vcO0u#x%tf9Yy/0GI#AVk*FW",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_009() {
    t(
        9,
        "example.org",
        "user@example.org",
        "password",
        100000,
        12,
        &[
            "]=~+<<.'^]/'",
            "293028887842",
            "_8^3=2\"2!_}4",
            "ODZHCADPTFNE",
            "]V`}FTKQ^.)~",
            "MPH573Z7W16M",
            "?%IQ$Q8&`^6Q",
            "odzhcadptfne",
            "]v`}ftkq^.)~",
            "mph573z7w16m",
            "?%iq$q8&`^6q",
            "OOzuDkDXmImi",
            "KzOn.Q(.xQJP",
            "YEl5L0C3QtLm",
            ")r~=gS9/=N`m",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_010() {
    t(
        10,
        "example.org",
        "user@example.org",
        "password",
        100000,
        16,
        &[
            "]{=~+<<.'^]'/#*[",
            "2932888784202407",
            "_8^38=2!_}4)*:$(",
            "MODZHCADTFNEPSBL",
            "]V`}F%TK.)~-+EJN",
            "MLP5373ZW16M3OKM",
            "?|%IQ$78`^Q)<T?6",
            "modzhcadtfnepsbl",
            "]v`}f%tk.)~-+ejn",
            "mlp5373zw16m3okm",
            "?|%iq$78`^q)<t?6",
            "xEOOzuDkXmIiMocd",
            "|KPzOQ(.xQPblqiI",
            "Y3l5L0CtQLmDHZg7",
            ")r%~==N`4mH;o7v+",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_011() {
    t(
        11,
        "example.org",
        "user@example.org",
        "password",
        100000,
        32,
        &[
            "]=~+<<.'^]'/#*[{~:(:#-~@;\\+_\"%<|",
            "29322888784202074826236311658937",
            "_8^3=2!_}4)*6$({/_9>;,{?\"!3?=4<\\",
            "ODZHCADTFNEPSBLMXQSNUQKBIFPVBMHM",
            "]V`}FTK=.)~-+JNC(%JPL/G<BYDH?QBO",
            "MP573ZHW16M3OKM3OSSYKXO6Y00CB35W",
            "?%IQ$8`^Q)<?6VOMT.7.3>5MT-T$0B*K",
            "odzhcadtfnepsblmxqsnuqkbifpvbmhm",
            "]v`}ftk=.)~-+jnc(%jpl/g<bydh?qbo",
            "mp573zhw16m3okm3ossykxo6y00cb35w",
            "?%iq$8`^q)<?6vomt.7.3>5mt-t$0b*k",
            "OOzuDkXmvIiMocdxCxitTmvLwrHhahhl",
            "KzOw%Q(.xQPlqiIV>kWHHzw~Cd*A$cc}",
            "Yl5L0CQLmDZg71Q3O46gedrNNRvXey2g",
            ")Ir~==N`m;o7+R?Jp6=|QbH/Al'3%D'x",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_012() {
    t(
        12,
        "example.org",
        "user@example.org",
        "foobar",
        1,
        12,
        &[
            "#~[={=<'/\\#>",
            "242832522353",
            "[(4^{:.158,5",
            "CORKECCEVAXM",
            "KK/%-}~'Z'^W",
            "04074Q3SZELA",
            "OS;{2942%G\\B",
            "corkeccevaxm",
            "kk/%-}~'z'^w",
            "04074q3szela",
            "os;{2942%g\\b",
            "VcursbxYvmkt",
            "[nY\"lVu:MJ*\"",
            "ml7yMngDM3eg",
            "46A}AH>n},Y;",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_013() {
    t(
        13,
        "example.org",
        "user@example.org",
        "foobar",
        1,
        16,
        &[
            "%#~[={=<'/#>\\(.#",
            "2428332523532551",
            "[(84^:.<18,5&9:{",
            "CORKECCEVYAMXQNJ",
            "K/%Y-}~'Z'WEQ)#I",
            "04G7343SZELAEHHJ",
            "KS;{298=2G\\B8Z?V",
            "corkeccevyamxqnj",
            "k/%y-}~'z'weq)#i",
            "04g7343szelaehhj",
            "ks;{298=2g\\b8z?v",
            "cuarbDxYvmktSXdU",
            "[Ylu[:MJ*sJ\"hd&L",
            "ml7ysMnDQe4g4VsV",
            "6A0QH>#},Y;x7bd?",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_014() {
    t(
        14,
        "example.org",
        "user@example.org",
        "foobar",
        1,
        32,
        &[
            "#~@[={=<'/#>\\(.#%)_]?\\'$\\'/)!;~?",
            "24283252353255139877215363627193",
            "1[(4^:.18,5&9:{6=~3\"3':}<-;'[8.*",
            "CORKECCEVAMXQNJYHMCITKNOHCTPHVMJ",
            "K/%-}~'Z'WEQ|#I=RSYRQ~F~%'_WY|~^",
            "04743SZ1ELAEHHJIPL4NS6HEOREHGUIT",
            "SA;{292G\\B8Z-?V8QYR15'*|59.]$\\*A",
            "corkeccevamxqnjyhmcitknohctphvmj",
            "k/%-}~'z'weq|#i=rsyrq~f~%'_wy|~^",
            "04743sz1elaehhjipl4ns6heorehguit",
            "sa;{292g\\b8z-?v8qyr15'*|59.]$\\*a",
            "cZurbxYvmktSXdUAbyEipTpAlJXvsZbX",
            "[Ylu:MJ*\"hd&L?N)p+oN\"!dpff`UoFF\\",
            "mwl7yMnDe5g4VsVOtAJYyQmLSbZ8gDF3",
            "6A'H>},Y;xz7d?zi!OtaX#b]2[z01Y7X",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_015() {
    t(
        15,
        "example.org",
        "user@example.org",
        "foobar",
        8,
        12,
        &[
            "!,@'=~/@]&+-",
            "299825246576",
            "+8\"6_{>\"*9*<",
            "IGXWHVMQZJUC",
            "`O\"\\;?X$*W<)",
            "6IIK0H89ZI44",
            "^2I%+)Z]]^*)",
            "igxwhvmqzjuc",
            "`o\"\\;?x$*w<)",
            "6iik0h89zi44",
            "^2i%+)z]]^*)",
            "iQfGiNUfzswp",
            "uF+o:.,\\u^Jj",
            "1aH65m7NCyk7",
            "cLg0iGxb9]?H",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_016() {
    t(
        16,
        "example.org",
        "user@example.org",
        "foobar",
        8,
        16,
        &[
            "!,!@'=/@]&+-~-~_",
            "2998254657652200",
            "+8\"6_{>**<*{&2|9",
            "IGXWJHVMQZJCUVGG",
            "O\"S\\.;?$*W<)JA,X",
            "62IK0H8N9ZI4E8I5",
            "%1+;)Z]]^*)AU;ZJ",
            "igxwjhvmqzjcuvgg",
            "o\"s\\.;?$*w<)ja,x",
            "62ik0h8n9zi4e8i5",
            "%1+;)z]]^*)au;zj",
            "isQfGiUfzspWtTZM",
            "u%R:a.,\\u^Jjm$IB",
            "a6i5m7NCMk7aB8qL",
            "cYqLg0xb]Hg^@)9z",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_017() {
    t(
        17,
        "example.org",
        "user@example.org",
        "foobar",
        8,
        32,
        &[
            "!,@'=/@]&+-~-~_!!%;[}\"-&`<,]`=^|",
            "29982546576220056667999759938000",
            "+8\"{6_{>**<*{&9%>*\"~.0\\)3{/\"4(#\\",
            "IGXWHVMQZJCUVGGJBRYQTGCBKDNZDTIV",
            "O\"\\;?$*W\\<)JA,X[?%?+~}).`^RMD{%^",
            "M6IK0H89ZI4E8I5VVZR8GE13RE8SMSX3",
            "%+)Z]]^*)9A;ZJ4UM~`W.ITUL%G0?L76",
            "igxwhvmqzjcuvggjbryqtgcbkdnzdtiv",
            "o\"\\;?$*w\\<)ja,x[?%?+~}).`^rmd{%^",
            "m6ik0h89zi4e8i5vvzr8ge13re8smsx3",
            "%+)z]]^*)9a;zj4um~`w.itul%g0?l76",
            "iQfGiUfzspWtZMSmWoXOfmUsjpxQjpGv",
            "uC:.,\\u`^Jjm$IB#h\"NT]XiANYQjLw{_",
            "a65m7NCk7aeDBqLC9kUQQIy99646AFDc",
            "@cLg40xb]HJg^)z%<Ymw0R^$?Z?^}G>[",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_018() {
    t(
        18,
        "example.org",
        "user@example.org",
        "foobar",
        32,
        12,
        &[
            "#,?{#&=)$[}^",
            "254414404327",
            "=9362|7_@5\\(",
            "AXBHRUVBIILT",
            ")W[`[HJ@DH$&",
            "Z5K0T4O3DI8T",
            "R[%SC*Z2C#!U",
            "axbhruvbiilt",
            ")w[`[hj@dh$&",
            "z5k0t4o3di8t",
            "r[%sc*z2c#!u",
            "AYgRklsShtAS",
            "=:>QAq@c$TyQ",
            "EW2i4Lw2Jfxl",
            "\\qF:lk0fHkw+",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_019() {
    t(
        19,
        "example.org",
        "user@example.org",
        "foobar",
        32,
        16,
        &[
            "#,?{#&=)[}^$~}?&",
            "6244144043275822",
            "=932|\\7_5\\5(!^-,",
            "AXBHRUVIIJLTBWAQ",
            ")W`[HJ@$H$&PCAKN",
            "K0T4O3D1IK8TL23L",
            "[SC*ZC#!9U7^E'L5",
            "axbhruviijltbwaq",
            ")w`[hj@$h$&pcakn",
            "k0t4o3d1ik8tl23l",
            "[sc*zc#!9u7^e'l5",
            "AYgRGtklsShStNOB",
            "=:QA@c$yQ^#Mjuu>",
            "E22i4YLwJxdlTqBk",
            "q:lkG0fH{k+e}y**",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_020() {
    t(
        20,
        "example.org",
        "user@example.org",
        "foobar",
        32,
        32,
        &[
            "#,?{#&=)[}^$~}&?._,'\\|>+)(>{!^\\_",
            "24341440432758226533010556178188",
            "=932|7_5\\(!^-,,\\301*1-\\{7_#`82=\"",
            "AXBHRUVIILTBWAQJEDZVCRNFBPIUHVEJ",
            ")SW`[HJ@H$&PAK]N}{FZA;F,KPG\"!GT=",
            "K0T4O3DI8TL23LU0Q9IXF48I5RTYTKX3",
            "[SC*ZC#!U37^ET5&BKU$1(7599S!A+\"|",
            "axbhruviiltbwaqjedzvcrnfbpiuhvej",
            ")sw`[hj@h$&pak]n}{fza;f,kpg\"!gt=",
            "k0t4o3di8tl23lu0q9ixf48i5rtytkx3",
            "[sc*zc#!u37^et5&bku$1(7599s!a+\"|",
            "AYgRklsShStZNOBtdjKNxVtDmVYmoVIo",
            "=:QA@c$yQ#ju>SncN\\B?]|&fk<HSF(fT",
            "1E2ih4LwJxlTqBkfhdhUOJKwhbTYlgeh",
            "qT:lkfHk+e}**!:-x!qltq'1\")<Rp>[7",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_021() {
    t(
        21,
        "example.org",
        "user@example.org",
        "foobar",
        100000,
        12,
        &[
            "//::{\\?{)`!/",
            "669187161133",
            "4@:<%009\\~=-",
            "ETHIVAXPYBTU",
            "[DSJ*;\\RFFE\"",
            "K8NHOF1BPNLW",
            "=/..%$J(*6)H",
            "ethivaxpybtu",
            "[dsj*;\\rffe\"",
            "k8nhof1bpnlw",
            "=/..%$j(*6)h",
            "EWBhIWfVcmJU",
            "wUK+<-K%lDm*",
            "sZK34JIu7Aac",
            "6}DrHF|}n!y]",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_022() {
    t(
        22,
        "example.org",
        "user@example.org",
        "foobar",
        100000,
        16,
        &[
            "/:/::{\\{)`!/?[.\\",
            "6691816113373599",
            "4@~:%00\\~=-1@05%",
            "ETHIAXFPYBTUVEHN",
            "[DSJ;L[\\RFE\"\");>",
            "K9NHOF1OPNLWZYR4",
            "=/.?.$(*9)H|*AB%",
            "ethiaxfpybtuvehn",
            "[dsj;l[\\rfe\"\");>",
            "k9nhof1opnlwzyr4",
            "=/.?.$(*9)h|*ab%",
            "EWBhIWUfVmUCEmdh",
            "UK,<k-K%lm*%<BW$",
            "sK3JI7A0acguSNiz",
            "}Dr]H|n!]aNHl|0^",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_023() {
    t(
        23,
        "example.org",
        "user@example.org",
        "foobar",
        100000,
        32,
        &[
            "//::{\\{_)`!/?[.\\:<`%,\"=<*=,'@]%/",
            "66918161163373995344187152521309",
            "4@:%00\\~=-@05=%|;\"[+}9:&$#5\"-(\\@",
            "ETHIAIXPYBTUVEHNFTZXJADRSJBZWFSK",
            "[DASJ;\\RFE\"\");>|UML}@;*ZN=+H<%L+",
            "KNH2OF1PNLWZYR4AAHGETB2CFMC8D0HK",
            "=/..$(*)H|*A%$*GJ@].-,C8SUMCN'>#",
            "ethiaixpybtuvehnftzxjadrsjbzwfsk",
            "[dasj;\\rfe\"\");>|uml}@;*zn=+h<%l+",
            "knh2of1pnlwzyr4aahgetb2cfmc8d0hk",
            "=/..$(*)h|*a%$*gj@].-,c8sumcn'>#",
            "EWBqhIWfVmUCEdhmkGHqZKkiWiuzYfHa",
            "UK<t-K%lm*%<B$syos|].yTAxx!*:r'O",
            "sK3JI7AacuNizuUcwXdEM86IJMcpNwQO",
            "}DrH|n!]eaH|^L25yZCsYt&cvUbmx1/N",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_024() {
    t(
        24,
        "example.org",
        "user",
        "password",
        1,
        12,
        &[
            "^|$[}{<\"%~'}",
            "148283777289",
            "`{05.4&!))~;",
            "JGFCGTCETSAS",
            "+J]\\~HFYX_'F",
            "NDJQRMW6Q900",
            "FZF~XL;<S1+R",
            "jgfcgtcetsas",
            "+j]\\~hfyx_'f",
            "ndjqrmw6q900",
            "fzf~xl;<s1+r",
            "jqBXkvwgfZcW",
            "L*@aQAZIn?~k",
            "9hKWhyqI1piT",
            "zUk)y%311~$4",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_025() {
    t(
        25,
        "example.org",
        "user",
        "password",
        1,
        16,
        &[
            "^|$[/}{<\"%'}~[%[",
            "1348283777892888",
            "`{0~56.&))~;%|}-",
            "JGFGGTCETSASCRVU",
            "J]\\T~HFY_'F$\\X:&",
            "NDQRMW6Q90VTC75T",
            "4FZFL<;<OS+RJ&20",
            "jgfggtcetsascrvu",
            "j]\\t~hfy_'f$\\x:&",
            "ndqrmw6q90vtc75t",
            "4fzfl<;<os+rj&20",
            "hjqBXkvwfIcWGZtj",
            "L*@AZKxIn~,kqCBk",
            "9Why6fqIFpiTdaNl",
            "zyz%11~$4U{%m6<*",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_026() {
    t(
        26,
        "example.org",
        "user",
        "password",
        1,
        32,
        &[
            "^|$[}{<\"%'}~[%[/<>-`=>[=/->([#`_",
            "14828377789288831548615845059202",
            "`{05.4&))~;%|+}-0_.\\.')\"{{9+*;?_",
            "JGFGTCETSASCRVUGUNNSXENEICBJEPOC",
            "J]\\~HFYZ_'F$\\X&Z'_WMMCI_R$WS>F=#",
            "XNDQRMW6Q904VT5T6GJ9PBO9C9UOEOQ4",
            "FZFL;<S+RJ&20}H8,6#V4A!@'};I0(96",
            "jgfgtcetsascrvugunnsxeneicbjepoc",
            "j]\\~hfyz_'f$\\x&z'_wmmci_r$ws>f=#",
            "xndqrmw6q904vt5t6gj9pbo9c9uoeoq4",
            "fzfl;<s+rj&20}h8,6#v4a!@'};i0(96",
            "jqBXkvwfcWGZtjcheVLKAXpmSFJIjQBM",
            "L+*@AZIn~kqCBk\\\\;u/:C@lE'A{@W^YK",
            "9WhnyEqIp8iTdaNl9NqBHxOiTD0mL2om",
            "zy%11~$41%mV<*jm)gU\\*kZpHtw:~KK'",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_027() {
    t(
        27,
        "example.org",
        "user",
        "password",
        8,
        12,
        &[
            "]]-{--@[-&.+",
            "649437409729",
            "#_3.=89`'5.,",
            "MCWQGBZUQAXI",
            "+#}LTQ~;D[IH",
            "MDWBBX8PT8FD",
            "Q_B_O^:L0,<:",
            "mcwqgbzuqaxi",
            "+#}ltq~;d[ih",
            "mdwbbx8pt8fd",
            "q_b_o^:l0,<:",
            "mBfOpsUGRVpr",
            "mN*Gn+B^uuiF",
            "ID9AP5PGmps6",
            ";pw/7z>T1c]^",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_028() {
    t(
        28,
        "example.org",
        "user",
        "password",
        8,
        16,
        &[
            "]]-{--@[&.+$-;;>",
            "6943740972943514",
            "#7_3.=9`5.,~-@=&",
            "MCWQGBZUUAXIQMNM",
            "B+#LQ~;D[IH',~)<",
            "MDWBBXPT8DRAQN6Q",
            "2EQ_B_^L,<(:4L?7",
            "mcwqgbzuuaxiqmnm",
            "b+#lq~;d[ih',~)<",
            "mdwbbxpt8draqn6q",
            "2eq_b_^l,<(:4l?7",
            "mBfpsNUuGRVrpuaC",
            "mq\\NGn+^uiFQ}PE?",
            "I49iAPPGmp6SXuMu",
            ";p/7zZ6w>c^I#52G",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_029() {
    t(
        29,
        "example.org",
        "user",
        "password",
        8,
        32,
        &[
            "]]-{--@[&.+-;;>$]_)%<)\"^]=](;'>~",
            "69437409729431455355047205738730",
            "#/_3.=9`5.,-@=&,4_?8]|5(;!042457",
            "MCWQGBZUAAXIQMNMUHVQZEFFXWWQQOCU",
            "+#LQ~;(MD[IH,~)<T*(<G@{$%T|;IH+:",
            "MDWB5UBXPT8DRQNQMFID0AF5CGMK0U7M",
            "Q_B_^L,<:4L?7M8?9U^97S^U4(JW>DZ\\",
            "mcwqgbzuaaxiqmnmuhvqzeffxwwqqocu",
            "+#lq~;(md[ih,~)<t*(<g@{$%t|;ih+:",
            "mdwb5ubxpt8drqnqmfid0af5cgmk0u7m",
            "q_b_^l,<:4l?7m8?9u^97s^u4(jw>dz\\",
            "mBfpsUGRVrpuaZCUgSxmRcDHtacIhDvH",
            "mNGHn+^uiF%Q}E?=pA-KcqbgG_lOdBsR",
            "qI9A7PPGmp6SuDMu6ypyWy5dawVoSNLC",
            ";p/7z>c^MI52Gk;11g5%e^0<LD\\*iZd6",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_030() {
    t(
        30,
        "example.org",
        "user",
        "password",
        32,
        12,
        &[
            "'#\\&?~;@-~=?",
            "243454656733",
            "[.)6,(=&9[@7",
            "SWKEXMQMVXUZ",
            "U>%\"J{QNQA%A",
            "01SZ8FLMIWJ0",
            "8R8+/~A!8('&",
            "swkexmqmvxuz",
            "u>%\"j{qnqa%a",
            "01sz8flmiwj0",
            "8r8+/~a!8('&",
            "RsLpXHDsugwI",
            "^[l_Dz=`{GmE",
            "2ObKyrgLZPc4",
            "2aO}^v5)GX{$",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_031() {
    t(
        31,
        "example.org",
        "user",
        "password",
        32,
        16,
        &[
            "'#\\?~;@@-~=?&*?>",
            "2434546673357012",
            "[.),(=9[0@744$91",
            "SWKEXMQMVXZUVEYX",
            "U>%\"JQQA%UAR!}'{",
            "01S8ZFLIRWJ0ESNP",
            "-8KR8+/~2!'&!#PX",
            "swkexmqmvxzuveyx",
            "u>%\"jqqa%uar!}'{",
            "01s8zflirwj0esnp",
            "-8kr8+/~2!'&!#px",
            "sLpXHDugwIySSins",
            "Q[l_=`{Gm~E~Ay&=",
            "ObvKyrg8LZ4wNEX2",
            "2aOQ}k^0X{$b}'@O",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_032() {
    t(
        32,
        "example.org",
        "user",
        "password",
        32,
        32,
        &[
            "'#\\?~;@-~=?&[*?>@-,;~.*$>.&~;]]\"",
            "24345466733501272344095674640521",
            "[.),(=9[@0+74491%#4*(2'\"4*<,2:`@",
            "SWKEXMQMVXZUVEXYSULDCHGUUAOJBIPZ",
            "UT>%\"J-QQA%AR!'{U+P$'QY,(#H@WGTY",
            "01SZFLIWJ0ESNP32E866E40LKOV9G2HU",
            "8R8K+/~!'2&!#?PX+M3N4(G\"K$F.P8W~",
            "swkexmqmvxzuvexysuldchguuaojbipz",
            "ut>%\"j-qqa%ar!'{u+p$'qy,(#h@wgty",
            "01szfliwj0esnp32e866e40lkov9g2hu",
            "8r8k+/~!'2&!#?px+m3n4(g\"k$f.p8w~",
            "sLpXHDugwISinsyJRUJkgfvdpVkBVebW",
            "[l_=`{G=mE~BA&=OhU$|XrPq\"\"aWXS)^",
            "ObKyrgLZ4wNE2j7sLQNvuZT8U5wkhe7H",
            "2)aO}^X{K$b'@8Oo-;~`i+HvUH!QupyP",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_033() {
    t(
        33,
        "example.org",
        "user",
        "password",
        100000,
        12,
        &[
            "{'??*{{=.->(",
            "661939420538",
            "=7'4?-8_##*5",
            "WAOSTVRAXSCN",
            "A%%^(:LT^:U@",
            "QR9OUU7BYL0P",
            ")1-(AB5)[+%{",
            "waostvraxscn",
            "a%%^(:lt^:u@",
            "qr9ouu7byl0p",
            ")1-(ab5)[+%{",
            "ahelPzWYkpob",
            "CiwJwa\\pYv`N",
            "8o5gIpUCyqud",
            "GCz*16?j(Psn",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_034() {
    t(
        34,
        "example.org",
        "user",
        "password",
        100000,
        16,
        &[
            "{'??{{(=.->(*$,\"",
            "6193942053786780",
            "='4?_-83_#*55$:'",
            "AOSTVRKAXSCNWYQD",
            "A%;B%(:L^:U@R])#",
            "Q9OUU78BYLP7JZGB",
            "))-(B5)+M%7{4V%@",
            "aostvrkaxscnwyqd",
            "a%;b%(:l^:u@r])#",
            "q9ouu78bylp7jzgb",
            "))-(b5)+m%7{4v%@",
            "ahlzWYkpobEGHcTB",
            "C>iwJwapN`NXvS_N",
            "o5g7pUUCqrudUTho",
            "-GUC*1?kjsn(\"g3I",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_035() {
    t(
        35,
        "example.org",
        "user",
        "password",
        100000,
        32,
        &[
            "{'??{{=.->(*$,\"(!\\\"$'?]:,+*_(^<{",
            "61939420538678070881677393322917",
            "#='4?-8_#*55$:'</&6{<}6=.%%^2,`)",
            "AOSTVRAXSCNWYQDKSKNLKGOVAELFDVLM",
            "A%%(:L^:U@R])#\\KX<<=_\\AY{',PC:~X",
            "Q9UOUU7BYLP7JGB35Q0SU522H30UBCSJ",
            ")-(QB5)#+%{4V%@S;M.%W|\\{P64JU99D",
            "aostvraxscnwyqdksknlkgovaelfdvlm",
            "a%%(:l^:u@r])#\\kx<<=_\\ay{',pc:~x",
            "q9uouu7bylp7jgb35q0su522h30ubcsj",
            ")-(qb5)#+%{4v%@s;m.%w|\\{p64ju99d",
            "ahYlzlWYkpobEHTBcDOtSjyeYLwPPrAH",
            "CiwJwaDp`NXS_NlJu%k`GO>F$RosL)Pm",
            "o5gpUCqudUTphoV3JM9BsyrQ602eQA7q",
            "GC*1?jsn(\"gaIGDZB1W=e(ThuM=0RnTd",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_036() {
    t(
        36,
        "example.org",
        "user",
        "foobar",
        1,
        12,
        &[
            "\\~[/-?~`|@\\]",
            "976892335155",
            ",>#'\\5\"60|\\7",
            "LZIDSQNVCHEE",
            "DULK~W'AJI&H",
            "P8WZ7HM21T9D",
            "4H_6F9\"}V;:!",
            "lzidsqnvchee",
            "dulk~w'aji&h",
            "p8wz7hm21t9d",
            "4h_6f9\"}v;:!",
            "lRNvzexXgBgb",
            ",o/{r\"?ObPC!",
            "5ZqbyEx1yOWB",
            "\"uz#7;-zJ.Ag",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_037() {
    t(
        37,
        "example.org",
        "user",
        "foobar",
        1,
        16,
        &[
            "\\~[/-?`|@\\!]~?@;",
            "9376892335551311",
            ",>#'0\\5\"0|7=?'0-",
            "LIDSQNVCHEEZUYBJ",
            "DULK~WAII&HN-{@E",
            "P8WHM21T9D96GYZQ",
            "H69\"8}V;:!<H)Q}R",
            "lidsqnvcheezuybj",
            "dulk~waii&hn-{@e",
            "p8whm21t9d96gyzq",
            "h69\"8}v;:!<h)q}r",
            "lRNavzeYxBgbGygy",
            ",o/{}?ObP!TOcZOK",
            "ZqjbEx1y4WBLWI5u",
            "\"<u#-tz.AgHKj8=u",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_038() {
    t(
        38,
        "example.org",
        "user",
        "foobar",
        1,
        32,
        &[
            "\\~[$/-?`|@\\]~?@;!?/!%:-~--+@|@_,",
            "97689233555131136210917838320972",
            ",>#'\\5\"0|7=>'0-!<%\\&-1+-'331-{,)",
            "LIDSQNVCHQEEZUBJYMZKACAAEUPEPAZL",
            "DULKD~WAI&HN-@E[/S^A`_C)Q!|T<C@}",
            "P8WHM21T9D9GZKQIHRSHL2DW93A8PNS5",
            "H691\"}V;:!<Q}R>LAM<!X\"8)R7G!DUC&",
            "lidsqnvchqeezubjymzkacaaeupepazl",
            "dulkd~wai&hn-@e[/s^a`_c)q!|t<c@}",
            "p8whm21t9d9gzkqihrshl2dw93a8pns5",
            "h691\"}v;:!<q}r>lam<!x\"8)r7g!duc&",
            "lRNvzexBgbGygyaxzPlTCatnNQjFrwYu",
            ",o/{?ObP!TZOKMi[H|)p?}\"(+dT)n!>e",
            "ZqbExY1yWBWI5ut65qhvChYITZJErN34",
            "\"xu#-z.AgHj8=uRYkoq<ZMCta$Rbm[QT",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_039() {
    t(
        39,
        "example.org",
        "user",
        "foobar",
        8,
        12,
        &[
            "/%<})+(.?\"*^",
            "266429932801",
            "'1<,}5+(\"'+)",
            "OPKRFZATAQPU",
            "YTY.J/J\\=;UZ",
            "WKPR5UA2ALWR",
            "G#LI89:N>#L}",
            "opkrfzataqpu",
            "yty.j/j\\=;uz",
            "wkpr5ua2alwr",
            "g#li89:n>#l}",
            "oeSXqYYiFMlT",
            "'v(sM.\"C~(S\\",
            "UEr546NKuIbD",
            "0=Np}5xxnaz*",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_040() {
    t(
        40,
        "example.org",
        "user",
        "foobar",
        8,
        16,
        &[
            "$/%<})+(?\"*^./#*",
            "2642993280164770",
            "'1<,}+(3\"')7.,\"0",
            "OKRFZATAQPEUPSPE",
            "-YTYJ/J\\=B;Z'Z<Y",
            "WKRU2A2ALWRJLWW3",
            "&G#L9:N#L1}%FT>{",
            "okrfzataqpeupspe",
            "-ytyj/j\\=b;z'z<y",
            "wkru2a2alwrjlww3",
            "&g#l9:n#l1}%ft>{",
            "oSXqYiFMJlTpeZlA",
            "'!v(L.C~a(S\\I>iQ",
            "UEr54NKuYDR0Tuo2",
            "=Yp(5xnja6z*p&I\\",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_041() {
    t(
        41,
        "example.org",
        "user",
        "foobar",
        8,
        32,
        &[
            "/%<})+(?\"*^./#*$~;'?%\\@[#/\\.||!?",
            "26429932801677047571425114299415",
            "'1<,}+(\"')7.\"08>430028<%91@}?<\"%",
            "OKYRFZATAQPUPSPEEJZFJBPENJCYKIVC",
            "YFTYJ/J\\=;Z'Z<Y@&R{B\\B$GK@]SS[(A",
            "WKRUA72ALWRJWW3X3VP78RFTUCZ7CVC4",
            "G#4L9:NF#L}^%T>{>L7A\"_.+MSN1H!UW",
            "okyrfzataqpupspeejzfjbpenjcykivc",
            "yftyj/j\\=;z'z<y@&r{b\\b$gk@]ss[(a",
            "wkrua72alwrjww3x3vp78rftucz7cvc4",
            "g#4l9:nf#l}^%t>{>l7a\"_.+msn1h!uw",
            "oSwXqYiFMlTeZlXAPEEfVrpwLhrFUKwZ",
            "'v(.C~h(S\\I>iQAr\\>M&#F%tXCXIMY.A",
            "UErH5z74NKuDRTo2GEMQKNfUurppeGin",
            "=p5x6n>az*p&I\\>kF%MfZIv[2#Kq_z)W",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_042() {
    t(
        42,
        "example.org",
        "user",
        "foobar",
        32,
        12,
        &[
            "?=')@()</>#]",
            "889137103130",
            "/7]0$-;*#].-",
            "XGRBKQVHNKYT",
            "QM:,Z#`'-G_O",
            "MKZK7V577NZS",
            "M0X_G4$3,2}=",
            "xgrbkqvhnkyt",
            "qm:,z#`'-g_o",
            "mkzk7v577nzs",
            "m0x_g4$3,2}=",
            "GvNxuzoJXcbv",
            "y(kHBd-e`<+a",
            "s3vZqnSsWbtW",
            ";5G;%(3#Vm6A",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_043() {
    t(
        43,
        "example.org",
        "user",
        "foobar",
        32,
        16,
        &[
            "?='\\)@()</>]##'/",
            "8891271031303670",
            "/]0$-;*].-@0./4}",
            "MGRBKQVHNKYTXLLH",
            "QM:Z#`'-(U_O?LO#",
            "MKK1V57N7NZS5CPF",
            "M0_2G4$,2=^M:XQW",
            "mgrbkqvhnkytxllh",
            "qm:z#`'-(u_o?lo#",
            "mkk1v57n7nzs5cpf",
            "m0_2g4$,2=^m:xqw",
            "GvnNuzoXcbvXrpDg",
            "y(kH'-e`+aXz|OP'",
            "svZqsWbYtWVx1jCd",
            ";e*51;%Q(V6A/w^l",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_044() {
    t(
        44,
        "example.org",
        "user",
        "foobar",
        32,
        32,
        &[
            "?=')@()</>]##'/\\?=_+&%]-.]`*({;$",
            "88917103130367029512288232822728",
            "/]0$*-;*].-@0.}693~.|[_[<0]?=|#&",
            "GRBKQVHNKYTXLLHMWZKXIIEYCWOZMYIC",
            "Q*M:Z#`'-_O?LO#IZEL<GHH*G/H,{+@=",
            "MKKV5S77NZS5CPF1FXAO78O31T4ALKGZ",
            "M0_G4$,62=^MXW-EI]{PRLP/.1ZQ*\"~U",
            "grbkqvhnkytxllhmwzkxiieycwozmyic",
            "q*m:z#`'-_o?lo#izel<ghh*g/h,{+@=",
            "mkkv5s77nzs5cpf1fxao78o31t4alkgz",
            "m0_g4$,62=^mxw-ei]{prlp/.1zq*\"~u",
            "GvNuzoXcbLvXorpgNbIYrDwOqJsERvsg",
            "y(kH-e`+Ra|OP'd>v}LBWw\\?oaO@@bi&",
            "svZqsWf3btWVjCdnhVBwMlw3F2tzikjV",
            ";5;%(V-6A/ww^l0Agn4Mz}1>R-p\"*~<3",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_045() {
    t(
        45,
        "example.org",
        "user",
        "foobar",
        100000,
        12,
        &[
            ",_${$`&]<`+.",
            "131711459821",
            "*_50-!'4$_+$",
            "NZJYVXZMJOEX",
            "VP)(.UUJ=EF?",
            "T4U7LD5Z6A3O",
            "T+627GF|G3~}",
            "nzjyvxzmjoex",
            "vp)(.uuj=ef?",
            "t4u7ld5z6a3o",
            "t+627gf|g3~}",
            "NezPmgzsFwKL",
            "}tsvyIqWM;iE",
            "poAYFo3HdcxR",
            "\"OP7xjRR];{)",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_046() {
    t(
        46,
        "example.org",
        "user",
        "foobar",
        100000,
        16,
        &[
            "-,_${$`&]<`.+;#,",
            "1381711598214581",
            "*_|0-!4$_+9$7.9/",
            "NZRJYVXMJOEXZSVB",
            "VP)(UJ=EFE?[,\\DK",
            "T4UD5Z6A39OBL3PD",
            "TW+62G|G3}59\"7N;",
            "nzrjyvxmjoexzsvb",
            "vp)(uj=efe?[,\\dk",
            "t4ud5z6a39obl3pd",
            "tw+62g|g3}59\"7n;",
            "NzlPmgzsFwLeSeBt",
            "tcsvIqM;AiE;o($-",
            "poA9YoHdxREFs6We",
            "j\"OP2xR]T{)Z)I'0",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_047() {
    t(
        47,
        "example.org",
        "user",
        "foobar",
        100000,
        32,
        &[
            ",_${$`&_]<`.+;#,-@),`&_%$#=\"%~/'",
            "13171159821045818208944706508952",
            "*_0-!4$_+{$7.9/31~'_1%89_`!@62[>",
            "NZJYVXMJOEXZSVBRHBCWPGYIUENWZUMS",
            "V-P)G(UJ=EF?[\\DKWA$`D!_EUL\"&X.)A",
            "T4UD5Z6A3OBL3DFABJQD1P9GWZE88R8N",
            "T+62G|\\GR3}97N;)!4#\\L9VETRI#=QFW",
            "nzjyvxmjoexzsvbrhbcwpgyiuenwzums",
            "v-p)g(uj=ef?[\\dkwa$`d!_eul\"&x.)a",
            "t4ud5z6a3obl3dfabjqd1p9gwze88r8n",
            "t+62g|\\gr3}97n;)!4#\\l9vetri#=qfw",
            "NzPmgzsFwLeSXetLaRNEKtukwWIWxCKh",
            "tsvIqM;?iE;o(-=U@aXqOzG+q@mrzHWe",
            "poAYoHdxREF26beiN2ueQrK6m2KGI9iG",
            "\"OPxR]{)OsZ)I0n,&;?enbr8-%RJ)d^B",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_048() {
    t(
        48,
        "example.net",
        "user@example.org",
        "password",
        1,
        12,
        &[
            "_*%~~\")+!|[.",
            "288542537451",
            "{}@\"@_!':6\\\"",
            "IHPCHVKMACUA",
            "DO:Q`\"_\"\"O;R",
            "02MAHUPEHHVB",
            "R}1/`(;85C%^",
            "ihpchvkmacua",
            "do:q`\"_\"\"o;r",
            "02mahupehhvb",
            "r}1/`(;85c%^",
            "IQDDEqZIudrm",
            "MPsV(MmkRu)_",
            "YrsRUQL82P70",
            "62H/,<n^#igb",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_049() {
    t(
        49,
        "example.net",
        "user@example.org",
        "password",
        1,
        16,
        &[
            "_*%~>~\")+|[.!;\\%",
            "2885425345217545",
            "8{}@\"@_-!:\\\"=.%1",
            "IHPCVQKMACUAHNJA",
            "OQ`\"_\"\"O;R.<O\\^<",
            "0MHL0UPEHHVB6ZA3",
            "}/K(;8.5C%^8`KXZ",
            "ihpcvqkmacuahnja",
            "oq`\"_\"\"o;r.<o\\^<",
            "0mhl0upehhvb6za3",
            "}/k(;8.5c%^8`kxz",
            "IQDuDEqIdrRmUZiy",
            "bMPs^MmRNu)_Kn-&",
            "YsRQL2NP708NTPiU",
            "W32/,;<m^igbbpS>",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_050() {
    t(
        50,
        "example.net",
        "user@example.org",
        "password",
        1,
        32,
        &[
            "_*%~~\")+|[.!;\\\"%>\\$<[*(&})+,^#/'",
            "28854253451754520482452499849231",
            "{}@\"@_!:\\\"=.%1?5~;<`$=\"1\\41`=->:",
            "IHCPCVKMACUAHNJAQKVTOOLYTIZQAZNP",
            "OQ`\"_\"\"O;R.<^<-{X;OTCC?UIY~'Q_J>",
            "0MHKUPEHHVB6Z1A3PCZA4B7O4GCF3JJ9",
            "}|/(;85C%^`KXZC`^_UGWUH4A[D4ZK8L",
            "ihcpcvkmacuahnjaqkvtoolytizqaznp",
            "oq`\"_\"\"o;r.<^<-{x;otcc?uiy~'q_j>",
            "0mhkupehhvb6z1a3pcza4b7o4gcf3jj9",
            "}|/(;85c%^`kxzc`^_ugwuh4a[d4zk8l",
            "IQDDEqIdrmUZiyUVrqTOzjXfUawEAadY",
            "M$PsMmRu)_Kn-&tTau\"UeO+M\\pg?uX[z",
            "YsRQL2P70N1TPiUWBBEXjBTMaUMDbBGM",
            "2/1,<^igbGbpS>%:vd#_nv5c_f@5raLY",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_051() {
    t(
        51,
        "example.net",
        "user@example.org",
        "password",
        8,
        12,
        &[
            ",:[<.#'/,\"?~",
            "364950148571",
            "<?^0_(16=[]?",
            "XGCWUFCWPIZO",
            "?B,O#&-?U#|&",
            "1QBWGR461BWI",
            "T$,|I2V90!M|",
            "xgcwufcwpizo",
            "?b,o#&-?u#|&",
            "1qbwgr461bwi",
            "t$,|i2v90!m|",
            "xDNCrDYokyEv",
            "BKOo=P?KAi!l",
            "jHrE494LdGdM",
            "Bc5**bU*TdwP",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_052() {
    t(
        52,
        "example.net",
        "user@example.org",
        "password",
        8,
        16,
        &[
            ",:[<.'/,\"?|~#=/}",
            "3695018485714944",
            "<?^(16=[]?=-3!>'",
            "XGCWUCWPTIZOFERQ",
            "B,O#&-?#Z|&}M|'=",
            "1QBWR4V63BWIIECT",
            "$L|I2V9!M|7$=A/*",
            "xgcwucwptizoferq",
            "b,o#&-?#z|&}m|'=",
            "1qbwr4v63bwiiect",
            "$l|i2v9!m|7$=a/*",
            "xDuNCrDokEvyWMQw",
            "BKO=WKAi,!lqv(zr",
            "7jHrdE94dGMNRyIC",
            "1Bc*bU*wPRNkNj`z",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_053() {
    t(
        53,
        "example.net",
        "user@example.org",
        "password",
        8,
        32,
        &[
            ",}:[<.'/,\"?~#=/}|;~)(&$(/};{$}>$",
            "39695014857149448618698460014026",
            ")<?^(16=[]?=6!>'3}+*]_)|.._6(|,4",
            "XGCWUCWPIZOFERQTQJPYFCZWXSLGOVEX",
            "B,(O#&-?#|&}M|=,}'-<){[>J!X;*Y`'",
            "1QBWR46BWIIECTXL2IOFB3UA5WIKOJU6",
            "$9|I2V9!M|$=DA*)BG#WZP[}+*:&8S]B",
            "xgcwucwpizoferqtqjpyfczwxslgovex",
            "b,(o#&-?#|&}m|=,}'-<){[>j!x;*y`'",
            "1qbwr46bwiiectxl2iofb3ua5wikoju6",
            "$9|i2v9!m|$=da*)bg#wzp[}+*:&8s]b",
            "PxDNCrDokEvyMQwulmzMLenqQjFQbPHw",
            "BfKO=KAi!l?qv(r<hH.rnGFtRGNjlq+c",
            "hjHrE94dGMN9RyCXxYj5hfF0Isk9t6Wx",
            "Bc*bU*wPRNkz`2J(IqCHV+W@_cmpbu(U",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_054() {
    t(
        54,
        "example.net",
        "user@example.org",
        "password",
        32,
        12,
        &[
            ".`'!@\\'$|=@+",
            "777823276341",
            "\\25_/``4&2<}",
            "TVEUQEFBWQOV",
            "JOO-S`@~W@\"#",
            "J7AH7DWGX4O7",
            "^?L7<7,U_9!,",
            "tveuqefbwqov",
            "joo-s`@~w@\"#",
            "j7ah7dwgx4o7",
            "^?l7<7,u_9!,",
            "vcFYILxClxsR",
            "HR`Z'=Vo}K&;",
            "TCOHYzEi9gvC",
            "pFnK(N4GIi;J",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_055() {
    t(
        55,
        "example.net",
        "user@example.org",
        "password",
        32,
        16,
        &[
            "~.`'!@\\'$|@+=($+",
            "7782327638417196",
            "!\\2/``4&2<}0~),3",
            "VEUQEFBLWQOVTZWE",
            "JLOOS`@~@\"#YD=$N",
            "J7A4HDWGX47KMZD6",
            "^?7<,UU9`!,J2L9G",
            "veuqefblwqovtzwe",
            "jloos`@~@\"#yd=$n",
            "j7a4hdwgx47kmzd6",
            "^?7<,uu9`!,j2l9g",
            "vcFILxClrKxRszrM",
            "HR`ZH=}K&`;azc/&",
            "XTCOHEigvC5RboLA",
            "p5nK=NvGIT;JQ0Ex",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_056() {
    t(
        56,
        "example.net",
        "user@example.org",
        "password",
        32,
        32,
        &[
            ".`'!@\\'$|@&+=($+~=#(;_;;\\&/=#!~,",
            "77823276341719689954761910604903",
            "\\2/``4&2<}~),38+07-;:/@'^@4<{=5>",
            "VEUQEFBWQOVTZWELLGHBHZYAIPTVDIVK",
            "JOOS`@~@\"#YD=N~=GIB{L[;=?]_K;\\<D",
            "J7AHDWGX47MZD6CAKYYJS24BYW7LJV39",
            "^?7<,FU91!,J2L+G[E'K}%}WIZ.DPH{C",
            "veuqefbwqovtzwellghbhzyaiptvdivk",
            "joos`@~@\"#yd=n~=gib{l[;=?]_k;\\<d",
            "j7ahdwgx47mzd6cakyyjs24byw7ljv39",
            "^?7<,fu91!,j2l+g[e'k}%}wiz.dph{c",
            "vcEFILxClxRszorMrfwpOqIvDKcovcCN",
            "xHR`Z=}K&;$ac/&tYky'hAAYyh}ATLYM",
            "TCOnHEigvCRUbLAqs4hHNYQpKBmXFhUk",
            "pnKNGI;JN1Q0ExvJ=&Ts?Q-\"#]Z{#B^t",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_057() {
    t(
        57,
        "example.net",
        "user@example.org",
        "password",
        100000,
        12,
        &[
            "-%+==^;?_.'#",
            "218845570605",
            "#]:<$\"=8'4(@",
            "UAWGTIVRGZHK",
            "/OI$((#)N\\Y<",
            "AXZLGWX5FYVH",
            "!GZB#4PW(BD]",
            "uawgtivrgzhk",
            "/oi$((#)n\\y<",
            "axzlgwx5fyvh",
            "!gzb#4pw(bd]",
            "usAFxRksgYVf",
            "m{q*>!c^K?mA",
            "eSILO9eRUVqa",
            "YO87+\\93(a)B",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_058() {
    t(
        58,
        "example.net",
        "user@example.org",
        "password",
        100000,
        16,
        &[
            "-%+'==^;?_'#./+>",
            "2185845570650325",
            "#9]*:<$\"=8(@_!!=",
            "UZAWGTIVGZHKRKTL",
            "/OI$(#)\\RY<;*}GF",
            "AXZRLGX6FYVHINIF",
            "!GZB9PW(B]P|#GK,",
            "uzawgtivgzhkrktl",
            "/oi$(#)\\ry<;*}gf",
            "axzrlgx6fyvhinif",
            "!gzb9pw(b]p|#gk,",
            "uAFxRksghVUfszQe",
            "m{qS*>!?mAAOju`@",
            "SILeRUV8qDaEzqI6",
            "O87+\\z3[(B5u4C?$",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_059() {
    t(
        59,
        "example.net",
        "user@example.org",
        "password",
        100000,
        32,
        &[
            "-%+=?=^;?_'#./+>')(-'^|%<?{.)!||",
            "21884557065032558224316010904404",
            "4#]:%<$\"=8(@_!!=~3\"!=@'~9{4+4$\"]",
            "UAWGTIVGZHKRKTLZKGCVDWJYVZJWRAIU",
            "/OI$(#)\\Y<*}GF@^:/@E^QO._?IZC&U%",
            "AXZLGXF7YVHINIFVZKEBWKX53IV2QOYY",
            "!GZBPW(B]P|>G,!+R0!'.-8M>5RW#\"94",
            "uawgtivgzhkrktlzkgcvdwjyvzjwraiu",
            "/oi$(#)\\y<*}gf@^:/@e^qo._?izc&u%",
            "axzlgxf7yvhinifvzkebwkx53iv2qoyy",
            "!gzbpw(b]p|>g,!+r0!'.-8m>5rw#\"94",
            "uAFxRksgVfgszQeZhkfHUDuQWJtRElID",
            "m{q*>!?mAAnOj@O?x;V]Hf%OgI_DW*:G",
            "SILeWRUVqaEzI6UI9Xm6ecUEIWEDUe8y",
            "O87+\\31(B.u4?$:-4`na\\)H7~/\"{\\J0X",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_060() {
    t(
        60,
        "example.net",
        "user@example.org",
        "foobar",
        1,
        12,
        &[
            "^!\"[)/=[[~^<",
            "443586298624",
            "1/}/$7@'8)>0",
            "SNTSEREYIUEY",
            "A>!.EAKA[RA}",
            "MFVWQ61B6PWP",
            "6{?SP[A4H]O<",
            "sntsereyiuey",
            "a>!.eaka[ra}",
            "mfvwq61b6pwp",
            "6{?sp[a4h]o<",
            "SRTrPGTgRajf",
            "y+?`<scgHvAm",
            "iouLam0X0MtF",
            "O-$m&OR)1tzP",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_061() {
    t(
        61,
        "example.net",
        "user@example.org",
        "foobar",
        1,
        16,
        &[
            "!\"[)/=[[-~^<^[_;",
            "4443586298642575",
            "/}/$7@'80>0&<<;[",
            "SNTSEEYIUEYRLZLU",
            "A\"!.EKA[RA}L;SE]",
            "4MFWQ6BN6PWPHE8U",
            "6{?SP[AH<S=3Y%AD",
            "sntseeyiueyrlzlu",
            "a\"!.eka[ra}l;se]",
            "4mfwq6bn6pwphe8u",
            "6{?sp[ah<s=3y%ad",
            "STrmPGETgRjfAILk",
            "y+`]<sgHvgmMQ\\jW",
            "iSo9gLamX0tFEdzK",
            "!O-4$&OtxzPO&QyT",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_062() {
    t(
        62,
        "example.net",
        "user@example.org",
        "foobar",
        1,
        32,
        &[
            "!\"[)/=[[~^<^@[_;-:*$]}&=\\~?&?'!-",
            "44358629864257542531907941801109",
            "/}/$7@'8>0<<;[+&6}&:8:.&-?/6&2=_",
            "SNTQSEEYIUEYRLZULWXZYNONURDNUDPZ",
            "A!._EKA[RXA};SE]JY.+@X&:<KC[FBP;",
            "MFWQ6B6PWPHNE8UVQ6527G7LBQTYU8VJ",
            "6{?SP[AH<=YADG-U>G2*D&1T7M$GT`_`",
            "sntqseeyiueyrlzulwxzynonurdnudpz",
            "a!._eka[rxa};se]jy.+@x&:<kc[fbp;",
            "mfwq6b6pwphne8uvq6527g7lbqtyu8vj",
            "6{?sp[ah<=yadg-u>g2*d&1t7m$gt`_`",
            "STrPGTgRjfAIKLkmpzvPuRhLEyDDWQbY",
            "y+`<scgHvmM\\jWwCu-~%YDL$\"\"H):s.b",
            "7ioLMamX0tFEdzjKCr3ImBWCDanDKBfV",
            "O-$&'DOtzPO&yT^0IWB&7AE;y,9S;Wv|",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_063() {
    t(
        63,
        "example.net",
        "user@example.org",
        "foobar",
        8,
        12,
        &[
            "/\"&$]%?!.(/*",
            "078358504697",
            "-5!|*?1{&{\"|",
            "WQQBDMAWBYTH",
            "ML|@D,QA>XR=",
            "KVX3AY6RCXYV",
            "+U\\/5|NTOHWM",
            "wqqbdmawbyth",
            "ml|@d,qa>xr=",
            "kvx3ay6rcxyv",
            "+u\\/5|ntohwm",
            "wIxNHAatPyFU",
            "n:wAPSE:_u]U",
            "OPiHciJLY58T",
            "y,\\qPq1FO8$(",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_064() {
    t(
        64,
        "example.net",
        "user@example.org",
        "foobar",
        8,
        16,
        &[
            "/&$]%?!.(/*\"*!>^",
            "0783585049767846",
            "-!/|*?1{&{|@1_}7",
            "WQQDMAWBYTZHBBSS",
            "ML`@W,QA>XR=\"\\S<",
            "KVX3AYRCXV9IKYRR",
            "+U\\/NTOHM=A8,K@%",
            "wqqdmawbytzhbbss",
            "ml`@w,qa>xr=\"\\s<",
            "kvx3ayrcxv9ikyrr",
            "+u\\/ntohm=a8,k@%",
            "wIxNAutPyFUAVQtI",
            "wAPS:_u]|U<Rv\\Z?",
            "fOPiHcLAY5T09V9m",
            "yy<,q11FOJ$(qtDA",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_065() {
    t(
        65,
        "example.net",
        "user@example.org",
        "foobar",
        8,
        32,
        &[
            "/&$]%?!.(/*>\"*!^>-;'-=<}->,-$];(",
            "07835850497674688592581276914628",
            "-!|*?1{&{|@_}75,{\\~~'3_%<8#30?={",
            "WQQDMAWBYTHBBSSZBCUCNMGCXUOGXNZB",
            "ML@,I,QA>XR=\"\\S<[WOQZH/FYKFR+N:S",
            "KVX53AYRCXVIYRRYI3JA3FZDVSGOUGRK",
            "+U\\/XN^TO4HMA,@%GH2]~;{4<YP7@I'{",
            "wqqdmawbythbbsszbcucnmgcxuogxnzb",
            "ml@,i,qa>xr=\"\\s<[woqzh/fykfr+n:s",
            "kvx53ayrcxviyrryi3ja3fzdvsgougrk",
            "+u\\/xn^to4hma,@%gh2]~;{4<yp7@i'{",
            "wIxNAtPyFUArQtIUxTVRRzSDktyTqnmn",
            "wAPYS:_u]gU<\\'Z?\\cVqR\\Sce^pjrC+=",
            "OPiHcLY5MT0V9mLSpXykORfn0E059b9p",
            "y,q1F\\O$t(qtDAurFg&e1>u1\\2Nc|Kuj",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_066() {
    t(
        66,
        "example.net",
        "user@example.org",
        "foobar",
        32,
        12,
        &[
            "%?*-<?>)=}.?",
            "480093514921",
            "/)-')/1(6))2",
            "ORVBWYPZXJHZ",
            "%N.:Q&<>:(%>",
            "YH19CYJG34HA",
            "A1C7-9[*#L;C",
            "orvbwypzxjhz",
            "%n.:q&<>:(%>",
            "yh19cyjg34ha",
            "a1c7-9[*#l;c",
            "OVLGtwwCOxHy",
            "qyZVP)HB=BT#",
            "i2oe1sLTEy2Q",
            "uHA^0r\\0~db_",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_067() {
    t(
        67,
        "example.net",
        "user@example.org",
        "foobar",
        32,
        16,
        &[
            "%?*-?>~)=}.?<}-@",
            "4800935192149562",
            "/)-')/(6)2$]*%95",
            "ORVBYPZXJHZWGWNH",
            "%N.:&F*<>(%>{U#D",
            "YH192DCYJG3APZRE",
            "A7(-92[*C#LC-`XU",
            "orvbypzxjhzwgwnh",
            "%n.:&f*<>(%>{u#d",
            "yh192dcyjg3apzre",
            "a7(-92[*c#lc-`xu",
            "OAVLGwwfCxHythyq",
            "<EyZVHB=gBT#g-FP",
            "i24Nkoe1sTEQo2pg",
            ">DuA\\0~d8b_cH.N|",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_068() {
    t(
        68,
        "example.net",
        "user@example.org",
        "foobar",
        32,
        32,
        &[
            "%?*-?><)=}.?<}-@~&:<)%$\"|<!?'(.@",
            "48400935192149625381248929022151",
            "/)-')/(6)2$7]%5(|\"65$?//\\/|5$?*!",
            "ORVBYPZXJHZWGNHWUYTKSDPJRDQFBYPX",
            "%N.:&#<>(%>{U#DR|/T(!&AI@IG[M<NA",
            "YH19CYJG3APZREYHMFBNN8IMX2J2Z13X",
            "A#7-9[*#LC-`XJU7_<M3.T0,^IW%G}MV",
            "orvbypzxjhzwgnhwuytksdpjrdqfbypx",
            "%n.:&#<>(%>{u#dr|/t(!&ai@ig[m<na",
            "yh19cyjg3apzreyhmfbnn8imx2j2z13x",
            "a#7-9[*#lc-`xju7_<m3.t0,^iw%g}mv",
            "OVLGwwCxHythyqfaQACuUpYPvfikRtZf",
            "yZV*HB=hBT#g-FPwFDh>.-}u'F|g)IWW",
            "i2oe1GsTEQo2pqgyM2ziLaKZJny9Y5xG",
            "uA\\0~db_H.N|6_k(]-dLZB,Pb.(o,pwU",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_069() {
    t(
        69,
        "example.net",
        "user@example.org",
        "foobar",
        100000,
        12,
        &[
            "_?+%_:/;'/@!",
            "061254238432",
            ")+{$2+#`(.7#",
            "EFJGWCTCMMRY",
            "OK]CFNN\"S']V",
            "G45T3Y5KQ0HH",
            "'M;AP85R?7A_",
            "efjgwctcmmry",
            "ok]cfnn\"s']v",
            "g45t3y5kq0hh",
            "'m;ap85r?7a_",
            "EppuXOSxCgxa",
            "Hskumovdk<-P",
            "KkiaOop06coS",
            ";I%1bVP[gMuS",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_070() {
    t(
        70,
        "example.net",
        "user@example.org",
        "foobar",
        100000,
        16,
        &[
            "_?%_:/;'/@!+]!+]",
            "0125423843926028",
            ")+{?$2+#(.#<6*1|",
            "EFJGWCTCMMYYRODU",
            "OK]CYFNS']V,_:YX",
            "V4T35Y5KQ0HHY22P",
            "'AP85'NR?A_G14&`",
            "efjgwctcmmyyrodu",
            "ok]cyfns']v,_:yx",
            "v4t35y5kq0hhy22p",
            "'ap85'nr?a_g14&`",
            "EppuOSAxCgaXYGur",
            "sk>Aumvsdk-P{g_'",
            "kiarOo0coSTl9Urk",
            ";I%bwVP6gS{C;IoV",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_071() {
    t(
        71,
        "example.net",
        "user@example.org",
        "foobar",
        100000,
        32,
        &[
            "_?%_:/;'/@!+]!]+@]@#{?*[}_|:,\\]&",
            "01254238493260289026406848876104",
            ")+{$2+4#(.#}<*1|?8{9)=?}!![?8$5`",
            "EFJGWCTCMMYRODUYWBZJRYRFUPHMLEDO",
            "O(KR]CFNS']V,:YX[=ZQ`%%CG<FJ<(J-",
            "4T3Y5KQ0HHY22P9RFI196XSW2VN6WPK8",
            "'AVP85R?A_G1&5`<K>>B5F4[(J]Y,2&<",
            "efjgwctcmmyroduywbzjryrfuphmledo",
            "o(kr]cfns']v,:yx[=zq`%%cg<fj<(j-",
            "4t3y5kq0hhy22p9rfi196xsw2vn6wpk8",
            "'avp85r?a_g1&5`<k>>b5f4[(j]y,2&<",
            "EppjuOSxCgaXYGrunLjNxnfoyVESVknz",
            "skumvd+k-P{dg_'cxY\\u]K}fs`gbp$N:",
            "kiaOo0coSlUrk99wW6es0cZCmI3Yv154",
            ";I%bVPgSC;oVG7&p72/[x2'^Ka|QcV[<",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_072() {
    t(
        72,
        "example.net",
        "user",
        "password",
        1,
        12,
        &[
            "**:=[>.$}|<_",
            "330500449036",
            "`6{{'),7-435",
            "FILFOHPMUUOE",
            "(-`P}>})S-V.",
            "BK6H4WGP2WZ0",
            "2<7:Y\"Q&@<E#",
            "filfohpmuuoe",
            "(-`p}>})s-v.",
            "bk6h4wgp2wz0",
            "2<7:y\"q&@<e#",
            "lfrJaWsPVWDJ",
            "QLT?-:qd~kcj",
            "N1xiGAfaz8oA",
            "3n|u}%1S+E!m",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_073() {
    t(
        73,
        "example.net",
        "user",
        "password",
        1,
        16,
        &[
            "**:[>.$}|<_==}}|",
            "3305000490364673",
            "`6{{')-435,1/'06",
            "FIILFOHPUUOEMUSG",
            "(-`ZP}>}S-.*^L&T",
            "BK6HWGP22Z08D1LT",
            "<7:Y\"Q&@#U/K6.A4",
            "fiilfohpuuoemusg",
            "(-`zp}>}s-.*^l&t",
            "bk6hwgp22z08d1lt",
            "<7:y\"q&@#u/k6.a4",
            "fryJaAWsVWDJLhKJ",
            "LT?:qd~cj+<q()Aw",
            "Nxi3Gfa8oAXGhWaE",
            "3n|}%HlS8!mG#yk<",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_074() {
    t(
        74,
        "example.net",
        "user",
        "password",
        1,
        32,
        &[
            "**:[>.$}|<_==}|},)=*_{*[@>&|.**_",
            "33025004903646730051338529308185",
            "4`6{{')-435,'067^:.#@~9!*7|#>?*,",
            "FILHFOHPUUOEMUSGIGUMNHHDLLLXBKCJ",
            "(-`P}X>}S-.*L&T@WO!<O\"B,C,CBNG$N",
            "4BFK6HWGP2Z08D1TT4PEPTZBGNPP2VYO",
            "<\\7:Y\"QF&@#U/K4)Z]3W-!*{[U!F|5Z6",
            "filhfohpuuoemusgigumnhhdlllxbkcj",
            "(-`p}x>}s-.*l&t@wo!<o\"b,c,cbng$n",
            "4bfk6hwgp2z08d1tt4peptzbgnpp2vyo",
            "<\\7:y\"qf&@#u/k4)z]3w-!*{[u!f|5z6",
            "frJaWsVWDJLhKJyiacnQXaPxpHLZFEnT",
            "LT?:q/d~cj+()wiu>M$-!,k^)gCw:k%V",
            "NxiGAfa8oAXGhcEmwK7GPP8OG00nK1vL",
            "3En|}%S!m?Gyk<7<1Mt@ME8{Lu3lkjoA",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_075() {
    t(
        75,
        "example.net",
        "user",
        "password",
        8,
        12,
        &[
            "./~.?>]'\"{.(",
            "370796288098",
            ".4@]^6]-.[4#",
            "VQRURGEJUDBL",
            ",NS.R=|(`_|,",
            "3E0G12KHHTKG",
            "@I~*S07}\\M$(",
            "vqrurgejudbl",
            ",ns.r=|(`_|,",
            "3e0g12khhtkg",
            "@i~*s07}\\m$(",
            "vILikRHpsagR",
            "#y.p}o`NY;Bw",
            "2ZdIbWwtxU4H",
            "x;V:#E36D\"bo",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_076() {
    t(
        76,
        "example.net",
        "user",
        "password",
        8,
        16,
        &[
            ".-/~.?>]'{.(\"|)^",
            "3779628680980414",
            ".@]7^6]-[4#;6?2<",
            "VQURGEJGUDBLRTOH",
            "NSV.=|(`_(|,:V,E",
            "36E0GH2KHTKGJPT6",
            "@*SQ`05}\\M$(/G>I",
            "vqurgejgudblrtoh",
            "nsv.=|(`_(|,:v,e",
            "36e0gh2khtkgjpt6",
            "@*sq`05}\\m$(/g>i",
            "vILikTRasagRPdTG",
            ".pv}o`XY;Bw'*_}l",
            "ZdbIbWtx4H415sJc",
            ")xxV:#E3\"oX*G1lN",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_077() {
    t(
        77,
        "example.net",
        "user",
        "password",
        8,
        32,
        &[
            "./~.?>]'{.(\",|)^-%&*/$;/%[!:@$[;",
            "37796288098041467178379126349202",
            ".@]^6]-6[4#;62<*;=:#)*%(0(`)*^/0",
            "VQAURGEJUDBLRTOHGUQCLKSBDXUFQBXZ",
            "NS.=|(`_|,:NV,EH-_V.F'D|B$H(|\"%Y",
            "3E0G2KHTKGJPT6HVC4H7D8XINMYRQ6L0",
            "@*S0}\\M$(/HG>IKF'E\"@Z[}EZ3~8:'^,",
            "vqaurgejudblrtohguqclksbdxufqbxz",
            "ns.=|(`_|,:nv,eh-_v.f'd|b$h(|\"%y",
            "3e0g2khtkgjpt6hvc4h7d8xinmyrq6l0",
            "@*s0}\\m$(/hg>ikf'e\"@z[}ez3~8:'^,",
            "vILikRsagRPdTGAJmwwKfZbJZXGdRXMO",
            ".p}o`Y;B<wf'_}l(*>y~zC*nAg}Oq(%w",
            "Z8dSIbWtx4H45scDtzjX7KBzY0Eg6YGj",
            "xV\":#E3\"oX*glNxk\"\\QpD|oDn01w1#[J",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_078() {
    t(
        78,
        "example.net",
        "user",
        "password",
        32,
        12,
        &[
            "-!,>].+`|*/#",
            "882888202893",
            "0:6$!#~5(\"<{",
            "ISHVAQELIECI",
            "#EP;T+BWHMRR",
            "1MB147O9ORRH",
            ";1Y=!9C(HL0V",
            "ishvaqelieci",
            "#ep;t+bwhmrr",
            "1mb147o9orrh",
            ";1y=!9c(hl0v",
            "iwICrpdWWrId",
            "`WWlxM!O^Q_@",
            "eaZOk8GDEuA1",
            "-V(?U|;4bKkz",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_079() {
    t(
        79,
        "example.net",
        "user",
        "password",
        32,
        16,
        &[
            "!,>].+`|*/#~-&`]",
            "8582888228930801",
            "6$@!5#~5(\"<{)#^6",
            "ISHVAELIDECIQAEG",
            ")#EP;TWHMRRDS|RV",
            "MBA147O90ORH1TXE",
            ";@1Y=97(HLFVKC54",
            "ishvaelideciqaeg",
            ")#ep;twhmrrds|rv",
            "mba147o90orh1txe",
            ";@1y=97(hlfvkc54",
            "iwwILpdWWrIdrOWv",
            "WWxM!^TQ_@R<n_)z",
            "eaZkGDEgA1UIpc5R",
            "-(U|;(K1kz\\rcX'%",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_080() {
    t(
        80,
        "example.net",
        "user",
        "password",
        32,
        32,
        &[
            "!,>].+`|*/#-&`]~$&]#*\":{:`,!}??<",
            "88288822893080156928551939916695",
            "]6$!#~5(\"<{)#^6$(%`?7;%%{['9<]3)",
            "ISHVAELIECIFQAEGDZJQEBUHASSDDNZM",
            "#EP;KTWHMRR;D|RV#,(MC/?*`^E<F.@/",
            "MB147O9OZRH1TXEASPC9ZCR8SM7MXHPD",
            ";1Y=9(HLVKC545;C#),B\"(DT345RDV=J",
            "ishvaeliecifqaegdzjqebuhassddnzm",
            "#ep;ktwhmrr;d|rv#,(mc/?*`^e<f.@/",
            "mb147o9ozrh1txeaspc9zcr8sm7mxhpd",
            ";1y=9(hlvkc545;c#),b\"(dt345rdv=j",
            "iwqIpdWWrIdrOWvWSauzKImwCpHesgZu",
            "WFWxM!^Q_)@R_)bzZlTNv'PCM<w_T{Nq",
            "eaZkGD3EA1UpcRyf5v7WermMtUgqXcCm",
            "-(U|;Kkz\\r'%c:L,DA,mxSaVa1GGD[=/",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_081() {
    t(
        81,
        "example.net",
        "user",
        "password",
        100000,
        12,
        &[
            ".'&-%&&)+)+}",
            "183436930082",
            ".@376]:##=%%",
            "BOMQAJTLFAYH",
            ":=V(VQ?}}>WC",
            "PF8UTUM0R7KV",
            "7X~\"C|C7..?C",
            "bomqajtlfayh",
            ":=v(vq?}}>wc",
            "pf8utum0r7kv",
            "7x~\"c|c7..?c",
            "bqhJQJiYLfUF",
            ".R~RvjmLf!R<",
            "l9kTKf8D71S8",
            "jW1STli}(}?P",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_082() {
    t(
        82,
        "example.net",
        "user",
        "password",
        100000,
        16,
        &[
            ".'&-%&!&)++})&^.",
            "1834363004829209",
            "/.356]:##=%%,=>$",
            "XBOMAJTLFAYHQZZA",
            ":=`(VQ?}}WCV<}GU",
            "F8UTUM0RXKVF9UAZ",
            "P7X\"|>C8..?CEEC}",
            "xbomajtlfayhqzza",
            ":=`(vq?}}wcv<}gu",
            "f8utum0rxkvf9uaz",
            "p7x\"|>c8..?ceec}",
            "tbhQJiYLfRUFQraZ",
            ".RR{jmLf!a<(QyXu",
            "h29kTKfS8D18328B",
            "jShT>l}}9?Pc~AEI",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_083() {
    t(
        83,
        "example.net",
        "user",
        "password",
        100000,
        32,
        &[
            ".'&-%&&)++})&^.!)~\\'#+*../:&~_\"?",
            "18343630082920944912934133668885",
            ".36]:##=%%,=>$>)?$-\"*(=&\"*\\||44-",
            "BOTMAJTLFAYHQZZAXIUFPIRYPRWEWXDN",
            ":=(VSQ?}}WC<}GUL=[Q(SLIZ;R#C_}[F",
            "F8UTUM0RK7VFPUAZJMX7BCD92MHE1WUC",
            "7X\"|C^J.8.?CEEC},HSQ2#%1B{V*:=$}",
            "botmajtlfayhqzzaxiufpiryprwewxdn",
            ":=(vsq?}}wc<}gul=[q(sliz;r#c_}[f",
            "f8utum0rk7vfpuazjmx7bcd92mhe1wuc",
            "7x\"|c^j.8.?ceec},hsq2#%1b{v*:=$}",
            "bhQJiYLfUFQraZTIMXzijXdyTnjzgooR",
            ".R`VRjmLf!<(yXuG!kbOL,d<.Z%\\b\\R@",
            "9kTKf8D1D08328BhexHZRdj10EfwaNOu",
            "jSTl2}}G?Pc~E`I$hg|DBgs;?nmUfp~P",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_084() {
    t(
        84,
        "example.net",
        "user",
        "foobar",
        1,
        12,
        &[
            "!`%%{]\"$.]=_",
            "808705742253",
            "4\"%+2~`32)+8",
            "ONNEIHIJDSET",
            "#-CYUF~R\"|?.",
            "QAVEUDVY4SIJ",
            "60QSU1!T_|H}",
            "onneihijdset",
            "#-cyuf~r\"|?.",
            "qaveudvy4sij",
            "60qsu1!t_|h}",
            "UOgOkxmoGMEv",
            "ehfbLL%Fk(gv",
            "lo9X4xARHKQv",
            ".{Jr3.usRde@",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_085() {
    t(
        85,
        "example.net",
        "user",
        "foobar",
        1,
        16,
        &[
            "!`%%{]$~.]=_\"`{;",
            "8087057542235016",
            "4$%+2~`3)+82{3%?",
            "ONEIHIJTDSETNHLT",
            "#-~CYU~R\"|.VG'!;",
            "QAVEFUD1VYIJ0WSP",
            "6QUX1;T_|H}=0`G3",
            "oneihijtdsetnhlt",
            "#-~cyu~r\"|.vg'!;",
            "qavefud1vyij0wsp",
            "6qux1;t_|h}=0`g3",
            "OLgOkxmGMEkvokRJ",
            "<ehYfLFk(vgvBvNl",
            "o9XxAhHKQvZRU03X",
            "{J9rl.?sde@+|DY`",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_086() {
    t(
        86,
        "example.net",
        "user",
        "foobar",
        1,
        32,
        &[
            "!`%%{]$.]=_\"`{;~;>^#|~=!$?+^`-)$",
            "80870574223501465772833635347890",
            "4%(+2~`3)+8{03%?;<%4[?7^._)<'64>",
            "ONEIHIJDSETNHLTTMZOHXILETKCUKOXK",
            "#-CYU~R\"|.V'!;I[RMWK/`RC_{UI^|<=",
            "QAVEUD8VYIJ0WSPHQIN9VJBT7LALT40O",
            ")6QU1T_|H}T=`G3>)\\\\,}6\";6JA&31}/",
            "oneihijdsetnhlttmzohxiletkcukoxk",
            "#-cyu~r\"|.v'!;i[rmwk/`rc_{ui^|<=",
            "qaveud8vyij0wsphqin9vjbt7lalt40o",
            ")6qu1t_|h}t=`g3>)\\\\,}6\";6ja&31}/",
            "OgOkxmGSMEvokRJKsLwxdJjJxMrlUqIS",
            "ehfLFk(gvBvNl.#>FwR{H.iKQQxOz,#Z",
            "o89XxAHKQvZR0XFoodQvgWkaTEQafbwH",
            "{Jr.i3sde~@+|Y`TqU&Dy\\Gw!rkN2Tcm",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_087() {
    t(
        87,
        "example.net",
        "user",
        "foobar",
        8,
        12,
        &[
            "&&[-)*!:)]')",
            "550652710003",
            "9[(1>*[=}25#",
            "BSOSVZASWKEZ",
            "X~:|I_&_!S}G",
            "VM0JZT4M600S",
            "\"{ICR3WTMRU'",
            "bsosvzaswkez",
            "x~:|i_&_!s}g",
            "vm0jzt4m600s",
            "\"{icr3wtmru'",
            "bjXfVCEhUUDU",
            "j`J`SM\\atimL",
            "TS4BkBU1bOcZ",
            "3L8m}bN]MNK/",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_088() {
    t(
        88,
        "example.net",
        "user",
        "foobar",
        8,
        16,
        &[
            "&_&[-)*!:)')].`&",
            "5065927100035109",
            "9[(*[&=}25#8~$1%",
            "BSOVZASWRKEZSUHW",
            "X~:IK_&_!}G(M!|P",
            "VM80JT4VM00SZJVR",
            "\"ICRWTM$R'208D>Z",
            "bsovzaswrkezsuhw",
            "x~:ik_&_!}g(m!|p",
            "vm80jt4vm00szjvr",
            "\"icrwtm$r'208d>z",
            "bAjXfVlEUUDUhBOx",
            "jC`JS\\aftiL!x@!t",
            "TSkBU1bOaA7ZuG8h",
            "L8}bNNKt/e'VJ$7|",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_089() {
    t(
        89,
        "example.net",
        "user",
        "foobar",
        8,
        32,
        &[
            "&&[-)*!:)')].`&_}$?][\\));|``/)|)",
            "50652710003517099457531393052304",
            "9[(*[=}25#~$1%{}^\";!}!^6<\\.64=(3",
            "BSOVZASWKEZSUHWRBKKRZCFHPTTQYFOB",
            "X~:I_~&_!}GM!Q|P%D<FAHLDSRVLJOMX",
            "VM0JT4M00SZJVRJJDR797HMU439IUFGO",
            "\"ICRWT4MR'08>Z\\[S'[N8&ZUQH}^^?BY",
            "bsovzaswkezsuhwrbkkrzcfhpttqyfob",
            "x~:i_~&_!}gm!q|p%d<fahldsrvljomx",
            "vm0jt4m00szjvrjjdr797hmu439iufgo",
            "\"icrwt4mr'08>z\\[s'[n8&zuqh}^^?by",
            "bjjXfVEUUHDUhBOxlnpyYlTSKYSTQYVb",
            "j`JS\\aLtiL!x@tz)F=FtiCA$SinmeH/~",
            "TSkBU1bOZufGX8hczJ536oe63XrnSiKA",
            "L8}bNNKy/Ze'V|@d9n-Wv8Dc;<A'Cj,N",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_090() {
    t(
        90,
        "example.net",
        "user",
        "foobar",
        32,
        12,
        &[
            "?&^}==]^}.!\"",
            "049793505877",
            "4-<,:641};}4",
            "OJJPKMYEWJWM",
            "U+)?#+^IBINP",
            "2WU7OQPGC7X8",
            "EI'VBLAB*2}$",
            "ojjpkmyewjwm",
            "u+)?#+^ibinp",
            "2wu7oqpgc7x8",
            "ei'vblab*2}$",
            "ORviGkuaCTsW",
            "eGh^(]@K#%Gj",
            "2vPCNieB3OpP",
            "A3X36X:kCPi!",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_091() {
    t(
        91,
        "example.net",
        "user",
        "foobar",
        32,
        16,
        &[
            "?&^}==]^}.:\"!/@;",
            "0497935057978683",
            "4-<:64};}743!$8.",
            "OJJPKMYEWJMWSSFK",
            "U+?B#+@^IBIP~?Y:",
            "2TWU7OQPGX824ZXU",
            "EIUVBLA*7}$RX+>N",
            "ojjpkmyewjmwssfk",
            "u+?b#+@^ibip~?y:",
            "2twu7oqpgx824zxu",
            "eiuvbla*7}$rx+>n",
            "ORxUviuaCTsWkday",
            "eG(,]@K#%jZv*CtH",
            "2PSCi4eBOpPpLhxN",
            "AX236XkPQ!'y&g)A",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_092() {
    t(
        92,
        "example.net",
        "user",
        "foobar",
        32,
        32,
        &[
            "?&^}==]^}.\"!/@;:#++_&>$'].++/*({",
            "04979350577868395826850621876936",
            "4-<:64};}43!8.5-*^8`=)5\"-4[\\!7'5",
            "OJJPKMYEWJMWSFKSHOMINMPSGNRSJQEP",
            "U+^?#+^IBIP~?Y:V,(:)(&P#-(^>`F>{",
            "2WU7OQPGX82ZXU9ZZV5XO1L2YW5KJ4M5",
            "EIVBPLA*}$RX+N2CR\"NO=::CD:I9[#0^",
            "ojjpkmyewjmwsfkshominmpsgnrsjqep",
            "u+^?#+^ibip~?y:v,(:)(&p#-(^>`f>{",
            "2wu7oqpgx82zxu9zzv5xo1l2yw5kj4m5",
            "eivbpla*}$rx+n2cr\"no=::cd:i9[#0^",
            "ORviuaCTgsWkdayxkgtqYPVsqsNsIWWH",
            ":evG(]@K#%jZ*tHDMC)mYR,=M`tZ|O\"m",
            "2P6CRieBObpPLhxN7Gmu9uaFYrk9vluF",
            "MAX369?XkP!'g)AO]:V|hj<FrgEFcl5l",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_093() {
    t(
        93,
        "example.net",
        "user",
        "foobar",
        100000,
        12,
        &[
            ",|}_+~`\\(-{{",
            "707564090734",
            ":,{@\\>-5()9%",
            "DSJUVZQSJNQK",
            "@-C<|)F$$GGP",
            "0HVVPXZRLGA5",
            "(Y=R35#N^A^7",
            "dsjuvzqsjnqk",
            "@-c<|)f$$ggp",
            "0hvvpxzrlga5",
            "(y=r35#n^a^7",
            "edwpZPnTnudj",
            "=:k+v*zE*|kK",
            "1V91UVM0BGxm",
            "A\\6R$t2/lz*q",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_094() {
    t(
        94,
        "example.net",
        "user",
        "foobar",
        100000,
        16,
        &[
            ",|}_+?~\\(-{{`(/'",
            "7075614090347546",
            ":,{@\\>-)9%.)6#+!",
            "DSJLUVZQSJNKQSMA",
            "@-F[C|)F$$GP?R)E",
            "I0HVPXZRLGA5NFSH",
            "(&Y=5#N^A7`I|I1<",
            "dsjluvzqsjnkqsma",
            "@-f[c|)f$$gp?r)e",
            "i0hvpxzrlga5nfsh",
            "(&y=5#n^a7`i|i1<",
            "dwpZPnnudjQEJvyZ",
            ":,k+e*z*|KkK\"ip*",
            "1Vz1UVM0Bmh3wjA9",
            "\\6R$tB2[/zq&h_W7",
        ],
    );
}

#[test]
#[cfg_attr(debug_assertions, ignore)]
fn vectors_095() {
    t(
        95,
        "example.net",
        "user",
        "foobar",
        100000,
        32,
        &[
            ",|}_+~\\(-{{`(/'?*:~*.>`\"{<>&%(?^",
            "70756409031475461581714081463833",
            ":,{@\\>-)9%.)+!?0.?1#98/6<<@-,@6~",
            "DSJZUVZQSJNKQSMALVHDAKXVRHVTMIRU",
            "@-C|)F=$$GP?R)E&T(E*(|XY@\"]GFV$&",
            "HVPXZRLGA5NF1SHY6BNT50SX31PZIYCA",
            "(Y==5#N^A7`|I<7K(?UX^IHWT^C\"@*}2",
            "dsjzuvzqsjnkqsmalvhdakxvrhvtmiru",
            "@-c|)f=$$gp?r)e&t(e*(|xy@\"]gfv$&",
            "hvpxzrlga5nf1shy6bnt50sx31pziyca",
            "(y==5#n^a7`|i<7k(?ux^ihwt^c\"@*}2",
            "dwpZPnOnudjdEJyZvijwSaIPgnyAwxDO",
            ":k+*z|*|kK\"ip*eniR,YhAs+,_\\<Rc&n",
            "1V1UVM0Bmhwj9Lq1QtkR8iQPGg1FkfMD",
            "\\R$t2/zq&E_W7>;^1)$4T.0gflw]20FY",
        ],
    );
}
